language: julia
os:
  - linux
  - osx

julia:
  - 1
  - nightly

notifications:
  email: false

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
  exclude:
    - os: windows
      julia: nightly
      language: julia

  include:
    - os: windows
      language: sh
      filter_secrets: false
      before_install:
        - choco install julia

  allow_failures:
  - julia: nightly
  - os: windows

script:
  - julia --project --color=yes -e "import Pkg; Pkg.add(\"BinaryProvider\")"
  - julia --project --color=yes deps/build.jl --verbose
  - julia --project --color=yes -e "import Libdl; Libdl.dlopen(\"./deps/usr/lib/libhelicsSharedLib.dylib\")"
  - julia --project --color=yes -e "import Pkg; Pkg.build(verbose=true)"
  - cat deps/build.log
  - julia --check-bounds=yes --depwarn=no --inline=no --color=yes --project -e "import Pkg; Pkg.test(coverage=true);"

after_success:
  # push coverage results to Codecov
  - julia --project=docs/ -e 'import Pkg; Pkg.add("Documenter"); include("docs/make.jl")'
  - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
