@cenum HelicsCoreTypes::UInt32 begin
    HELICS_CORE_TYPE_DEFAULT = 0
    HELICS_CORE_TYPE_ZMQ = 1
    HELICS_CORE_TYPE_MPI = 2
    HELICS_CORE_TYPE_TEST = 3
    HELICS_CORE_TYPE_INTERPROCESS = 4
    HELICS_CORE_TYPE_IPC = 5
    HELICS_CORE_TYPE_TCP = 6
    HELICS_CORE_TYPE_UDP = 7
    HELICS_CORE_TYPE_ZMQ_SS = 10
    HELICS_CORE_TYPE_NNG = 9
    HELICS_CORE_TYPE_TCP_SS = 11
    HELICS_CORE_TYPE_HTTP = 12
    HELICS_CORE_TYPE_WEBSOCKET = 14
    HELICS_CORE_TYPE_INPROC = 18
    HELICS_CORE_TYPE_NULL = 66
    HELICS_CORE_TYPE_EMPTY = 77
    HELICS_CORE_TYPE_EXTRACT = 101
end

@cenum HelicsDataTypes::Int32 begin
    HELICS_DATA_TYPE_UNKNOWN = -1
    HELICS_DATA_TYPE_STRING = 0
    HELICS_DATA_TYPE_DOUBLE = 1
    HELICS_DATA_TYPE_INT = 2
    HELICS_DATA_TYPE_COMPLEX = 3
    HELICS_DATA_TYPE_VECTOR = 4
    HELICS_DATA_TYPE_COMPLEX_VECTOR = 5
    HELICS_DATA_TYPE_NAMED_POINT = 6
    HELICS_DATA_TYPE_BOOLEAN = 7
    HELICS_DATA_TYPE_TIME = 8
    HELICS_DATA_TYPE_CHAR = 9
    HELICS_DATA_TYPE_RAW = 25
    HELICS_DATA_TYPE_JSON = 30
    HELICS_DATA_TYPE_MULTI = 33
    HELICS_DATA_TYPE_ANY = 25262
end

@cenum HelicsFederateFlags::UInt32 begin
    HELICS_FLAG_OBSERVER = 0
    HELICS_FLAG_UNINTERRUPTIBLE = 1
    HELICS_FLAG_INTERRUPTIBLE = 2
    HELICS_FLAG_SOURCE_ONLY = 4
    HELICS_FLAG_ONLY_TRANSMIT_ON_CHANGE = 6
    HELICS_FLAG_ONLY_UPDATE_ON_CHANGE = 8
    HELICS_FLAG_WAIT_FOR_CURRENT_TIME_UPDATE = 10
    HELICS_FLAG_RESTRICTIVE_TIME_POLICY = 11
    HELICS_FLAG_ROLLBACK = 12
    HELICS_FLAG_FORWARD_COMPUTE = 14
    HELICS_FLAG_REALTIME = 16
    HELICS_FLAG_SINGLE_THREAD_FEDERATE = 27
    HELICS_FLAG_MULTI_THREAD_CORE = 28
    HELICS_FLAG_SINGLE_THREAD_CORE = 29
    HELICS_FLAG_REENTRANT = 38
    HELICS_FLAG_IGNORE_TIME_MISMATCH_WARNINGS = 67
    HELICS_FLAG_STRICT_CONFIG_CHECKING = 75
    HELICS_FLAG_USE_JSON_SERIALIZATION = 79
    HELICS_FLAG_EVENT_TRIGGERED = 81
    HELICS_FLAG_LOCAL_PROFILING_CAPTURE = 96
    HELICS_FLAG_CALLBACK_FEDERATE = 103
    HELICS_FLAG_AUTOMATED_TIME_REQUEST = 106
end

@cenum HelicsCoreFlags::UInt32 begin
    HELICS_FLAG_DELAY_INIT_ENTRY = 45
    HELICS_FLAG_ENABLE_INIT_ENTRY = 47
    HELICS_FLAG_IGNORE = 999
end

@cenum HelicsFlags::UInt32 begin
    HELICS_FLAG_SLOW_RESPONDING = 29
    HELICS_FLAG_DEBUGGING = 31
    HELICS_FLAG_TERMINATE_ON_ERROR = 72
    HELICS_FLAG_FORCE_LOGGING_FLUSH = 88
    HELICS_FLAG_DUMPLOG = 89
    HELICS_FLAG_PROFILING = 93
    HELICS_FLAG_PROFILING_MARKER = 95
    HELICS_FLAG_ALLOW_REMOTE_CONTROL = 109
    HELICS_FLAG_DISABLE_REMOTE_CONTROL = 110
end

@cenum HelicsLogLevels::Int32 begin
    HELICS_LOG_LEVEL_DUMPLOG = -10
    HELICS_LOG_LEVEL_NO_PRINT = -4
    HELICS_LOG_LEVEL_ERROR = 0
    HELICS_LOG_LEVEL_PROFILING = 2
    HELICS_LOG_LEVEL_WARNING = 3
    HELICS_LOG_LEVEL_SUMMARY = 6
    HELICS_LOG_LEVEL_CONNECTIONS = 9
    HELICS_LOG_LEVEL_INTERFACES = 12
    HELICS_LOG_LEVEL_TIMING = 15
    HELICS_LOG_LEVEL_DATA = 18
    HELICS_LOG_LEVEL_DEBUG = 21
    HELICS_LOG_LEVEL_TRACE = 24
end

@cenum HelicsErrorTypes::Int32 begin
    HELICS_ERROR_FATAL = -404
    HELICS_ERROR_EXTERNAL_TYPE = -203
    HELICS_ERROR_OTHER = -101
    HELICS_USER_EXCEPTION = -29
    HELICS_ERROR_INSUFFICIENT_SPACE = -18
    HELICS_ERROR_EXECUTION_FAILURE = -14
    HELICS_ERROR_INVALID_FUNCTION_CALL = -10
    HELICS_ERROR_INVALID_STATE_TRANSITION = -9
    HELICS_WARNING = -8
    HELICS_ERROR_SYSTEM_FAILURE = -6
    HELICS_ERROR_DISCARD = -5
    HELICS_ERROR_INVALID_ARGUMENT = -4
    HELICS_ERROR_INVALID_OBJECT = -3
    HELICS_ERROR_CONNECTION_FAILURE = -2
    HELICS_ERROR_REGISTRATION_FAILURE = -1
    HELICS_OK = 0
    HELICS_ERROR_USER_ABORT = 130
    HELICS_ERROR_TERMINATED = 143
end

@cenum HelicsProperties::UInt32 begin
    HELICS_PROPERTY_TIME_DELTA = 137
    HELICS_PROPERTY_TIME_PERIOD = 140
    HELICS_PROPERTY_TIME_OFFSET = 141
    HELICS_PROPERTY_TIME_RT_LAG = 143
    HELICS_PROPERTY_TIME_RT_LEAD = 144
    HELICS_PROPERTY_TIME_RT_TOLERANCE = 145
    HELICS_PROPERTY_TIME_INPUT_DELAY = 148
    HELICS_PROPERTY_TIME_OUTPUT_DELAY = 150
    HELICS_PROPERTY_TIME_STOPTIME = 152
    HELICS_PROPERTY_TIME_GRANT_TIMEOUT = 161
    HELICS_PROPERTY_INT_CURRENT_ITERATION = 258
    HELICS_PROPERTY_INT_MAX_ITERATIONS = 259
    HELICS_PROPERTY_INT_LOG_LEVEL = 271
    HELICS_PROPERTY_INT_FILE_LOG_LEVEL = 272
    HELICS_PROPERTY_INT_CONSOLE_LOG_LEVEL = 274
    HELICS_PROPERTY_INT_LOG_BUFFER = 276
    HELICS_PROPERTY_INT_INDEX_GROUP = 282
end

@cenum HelicsMultiInputModes::UInt32 begin
    HELICS_MULTI_INPUT_NO_OP = 0
    HELICS_MULTI_INPUT_VECTORIZE_OPERATION = 1
    HELICS_MULTI_INPUT_AND_OPERATION = 2
    HELICS_MULTI_INPUT_OR_OPERATION = 3
    HELICS_MULTI_INPUT_SUM_OPERATION = 4
    HELICS_MULTI_INPUT_DIFF_OPERATION = 5
    HELICS_MULTI_INPUT_MAX_OPERATION = 6
    HELICS_MULTI_INPUT_MIN_OPERATION = 7
    HELICS_MULTI_INPUT_AVERAGE_OPERATION = 8
end

@cenum HelicsHandleOptions::UInt32 begin
    HELICS_HANDLE_OPTION_CONNECTION_REQUIRED = 397
    HELICS_HANDLE_OPTION_CONNECTION_OPTIONAL = 402
    HELICS_HANDLE_OPTION_SINGLE_CONNECTION_ONLY = 407
    HELICS_HANDLE_OPTION_MULTIPLE_CONNECTIONS_ALLOWED = 409
    HELICS_HANDLE_OPTION_BUFFER_DATA = 411
    HELICS_HANDLE_OPTION_RECONNECTABLE = 412
    HELICS_HANDLE_OPTION_STRICT_TYPE_CHECKING = 414
    HELICS_HANDLE_OPTION_RECEIVE_ONLY = 422
    HELICS_HANDLE_OPTION_SOURCE_ONLY = 423
    HELICS_HANDLE_OPTION_IGNORE_UNIT_MISMATCH = 447
    HELICS_HANDLE_OPTION_ONLY_TRANSMIT_ON_CHANGE = 452
    HELICS_HANDLE_OPTION_ONLY_UPDATE_ON_CHANGE = 454
    HELICS_HANDLE_OPTION_IGNORE_INTERRUPTS = 475
    HELICS_HANDLE_OPTION_MULTI_INPUT_HANDLING_METHOD = 507
    HELICS_HANDLE_OPTION_INPUT_PRIORITY_LOCATION = 510
    HELICS_HANDLE_OPTION_CLEAR_PRIORITY_LIST = 512
    HELICS_HANDLE_OPTION_CONNECTIONS = 522
    HELICS_HANDLE_OPTION_TIME_RESTRICTED = 557
end

@cenum HelicsFilterTypes::UInt32 begin
    HELICS_FILTER_TYPE_CUSTOM = 0
    HELICS_FILTER_TYPE_DELAY = 1
    HELICS_FILTER_TYPE_RANDOM_DELAY = 2
    HELICS_FILTER_TYPE_RANDOM_DROP = 3
    HELICS_FILTER_TYPE_REROUTE = 4
    HELICS_FILTER_TYPE_CLONE = 5
    HELICS_FILTER_TYPE_FIREWALL = 6
end

@cenum HelicsTranslatorTypes::UInt32 begin
    HELICS_TRANSLATOR_TYPE_CUSTOM = 0
    HELICS_TRANSLATOR_TYPE_JSON = 11
    HELICS_TRANSLATOR_TYPE_BINARY = 12
end

@cenum HelicsSequencingModes::UInt32 begin
    HELICS_SEQUENCING_MODE_FAST = 0
    HELICS_SEQUENCING_MODE_ORDERED = 1
    HELICS_SEQUENCING_MODE_DEFAULT = 2
end

const HelicsInput = Ptr{Cvoid}

const HelicsPublication = Ptr{Cvoid}

const HelicsEndpoint = Ptr{Cvoid}

const HelicsFilter = Ptr{Cvoid}

const HelicsTranslator = Ptr{Cvoid}

const HelicsCore = Ptr{Cvoid}

const HelicsBroker = Ptr{Cvoid}

const HelicsFederate = Ptr{Cvoid}

const HelicsApp = Ptr{Cvoid}

const HelicsFederateInfo = Ptr{Cvoid}

const HelicsQuery = Ptr{Cvoid}

const HelicsDataBuffer = Ptr{Cvoid}

const HelicsQueryBuffer = Ptr{Cvoid}

const HelicsMessage = Ptr{Cvoid}

const HelicsTime = Cdouble

const HelicsBool = Cint

@cenum HelicsIterationRequest::UInt32 begin
    HELICS_ITERATION_REQUEST_NO_ITERATION = 0
    HELICS_ITERATION_REQUEST_FORCE_ITERATION = 1
    HELICS_ITERATION_REQUEST_ITERATE_IF_NEEDED = 2
    HELICS_ITERATION_REQUEST_HALT_OPERATIONS = 5
    HELICS_ITERATION_REQUEST_ERROR = 7
end

@cenum HelicsIterationResult::UInt32 begin
    HELICS_ITERATION_RESULT_NEXT_STEP = 0
    HELICS_ITERATION_RESULT_ERROR = 1
    HELICS_ITERATION_RESULT_HALTED = 2
    HELICS_ITERATION_RESULT_ITERATING = 3
end

@cenum HelicsFederateState::Int32 begin
    HELICS_STATE_UNKNOWN = -1
    HELICS_STATE_STARTUP = 0
    HELICS_STATE_INITIALIZATION = 1
    HELICS_STATE_EXECUTION = 2
    HELICS_STATE_FINALIZE = 3
    HELICS_STATE_ERROR = 4
    HELICS_STATE_PENDING_INIT = 5
    HELICS_STATE_PENDING_EXEC = 6
    HELICS_STATE_PENDING_TIME = 7
    HELICS_STATE_PENDING_ITERATIVE_TIME = 8
    HELICS_STATE_PENDING_FINALIZE = 9
    HELICS_STATE_FINISHED = 10
end

struct HelicsComplex
    real::Cdouble
    imag::Cdouble
end

struct HelicsError
    error_code::Int32
    message::Ptr{Cchar}
end

# Skipping MacroDefinition: HELICS_DEPRECATED __attribute__ ( ( deprecated ) )

const HELICS_BIG_NUMBER = 9.223372036854774e9

const HELICS_INVALID_DOUBLE = -1.0e49

