const HELICS_HAVE_MPI = 0
const HELICS_HAVE_ZEROMQ = 1
const BOOST_VERSION_LEVEL = 71
const HELICS_VERSION_MAJOR = 2
const HELICS_VERSION_MINOR = 3
const HELICS_VERSION_PATCH = 0
const HELICS_VERSION = "2.3.0"
const HELICS_VERSION_BUILD = ""
const HELICS_VERSION_STRING = "2.3.0 (2019-11-13)"
const HELICS_DATE = "2019-11-13"

